In [1]:
import numpy as np

In [3]:
import pandas as pd

In [21]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [22]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [7]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [9]:
model=Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [11]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.get_weights()

[array([[ 0.81521285,  1.0073787 ],
        [-0.1603905 ,  0.44830096]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.86370695],
        [-1.0921408 ]], dtype=float32),
 array([0.], dtype=float32)]

In [13]:
new_weights=[np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),np.array([0.,0.],dtype=np.float32),np.array([[0.1],[0.1]],dtype=np.float32),np.array([0.],dtype=np.float32)]


In [14]:
new_weights

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [15]:
model.set_weights(new_weights)

In [16]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [19]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [23]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 [==============================] - 1s 5ms/step - loss: 27.9134
Epoch 2/75
4/4 [==============================] - 0s 4ms/step - loss: 27.5996
Epoch 3/75
4/4 [==============================] - 0s 3ms/step - loss: 27.2456
Epoch 4/75
4/4 [==============================] - 0s 4ms/step - loss: 26.9384
Epoch 5/75
4/4 [==============================] - 0s 3ms/step - loss: 26.5790
Epoch 6/75
4/4 [==============================] - 0s 4ms/step - loss: 26.2076
Epoch 7/75
4/4 [==============================] - 0s 4ms/step - loss: 25.8410
Epoch 8/75
4/4 [==============================] - 0s 4ms/step - loss: 25.4959
Epoch 9/75
4/4 [==============================] - 0s 4ms/step - loss: 25.0856
Epoch 10/75
4/4 [==============================] - 0s 3ms/step - loss: 24.6640
Epoch 11/75
4/4 [==============================] - 0s 3ms/step - loss: 24.2429
Epoch 12/75
4/4 [==============================] - 0s 3ms/step - loss: 23.8245
Epoch 13/75
4/4 [==============================] - 0s 4ms/ste

In [24]:
model.get_weights()

[array([[0.37375712, 0.37375712],
        [0.36560962, 0.36560962]], dtype=float32),
 array([0.27237323, 0.27237323], dtype=float32),
 array([[0.37297356],
        [0.37297356]], dtype=float32),
 array([0.20463862], dtype=float32)]